on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
name: Continuous Integration
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 8, 11, 14 ]
    name: Java ${{ matrix.java }}
    steps:
      - uses: actions/checkout@master
      - name: Checkout submodules
        submodules: true
      - name: Setup java
        uses: actions/setup-java@master
        with:
          java-version: ${{ matrix.java }}
      - run: ./mvnw verify
      - run: ant test
